### ISSUE TITLE
Does this keeps user info safe on page refresh?

### ISSUE THREAD

**Issue by murli800** [signalpoint/angular-drupal#1]
Hi
Does this keeps user info safe on page refresh?

**Comment by signalpoint** [comment]
@murli800 Please clarify, I don't understand.

**Comment by murli800** [comment]
@signalpoint . I tried to develop angular app and for storing data i used Drupal. The challenge i came across is to keep user logged in on browser on page refresh. If i refresh the browser data stored in routeScope get deleted. 
So i want to know does this module handle it own its own or i need cookie to restore user info?

**Comment by signalpoint** [comment]
@murli800 Since Drupal uses cookie based authentication, the user should remain logged in as long as the session is valid. The trick is you need to call `drupal.connect()` in your app, which will then report to you which user account is currently logged in.

**Comment by murli800** [comment]
@signalpoint Thanks for your quick suggestion. I will use your this module and rewrite my code as  your code is much cleaner.
