### ISSUE TITLE
Merge with jDrupal?

### ISSUE THREAD

**Issue by kentr** [signalpoint/angular-drupal#23]
I've been looking at jDrupal 8.x-1.x, which appears much more full-featured & functional for interaction with D8 REST, and I've gotten a basic bridge working to turn jDrupal into an AngularJS service.

Am I correct in understanding that jDrupal has more support for D8 REST than angular-drupal does?  Would you consider merging them (like, making angular-drupal a wrapper around jDrupal)?  I would be glad to contribute what I've done so far on that front.

**Comment by signalpoint** [comment]
@kentr yes this would be great. jDrupal is a dependency for angular-drupal 8, so it does make sense to merge them, and just build a little Angular layer on top of jDrupal 8. Thank you for your interest on ideas on this!

**Comment by kentr** [comment]
Great.  Initial work is [here](https://github.com/kentr/angular-drupal/tree/8.x-1.x).  Not tested enough for a pr yet.

I don't see jDrupal in `bower.json` as a dependency.  How is the dependency defined?

**Comment by signalpoint** [comment]
@kentr Oh, it looks like it is only a dependency in my head, I guess I never actually wrote it down!

I was thinking of making the angular_drupal module for Drupal 8 dependent on the jdrupal module for Drupal 8.

What do you think? Feel free to add jdrupal to bower.json as a dependency, I haven't gotten that far yet.

**Comment by kentr** [comment]
Ok, I'll do that.

**Comment by kentr** [comment]
First steps on this are done.
