### ISSUE TITLE
user/login.json 404 (Not Found) with drupal.user_login

### ISSUE THREAD

**Issue by e2o** [signalpoint/angular-drupal#25]
I'm encountering this strange issue on D8 when i try to authenticate a user via the following method:

```
drupal.user_login('bob', 'secret').then(function(data) {
    //returned data here
});
```

I've enabled users as a REST resource like this:
![image](https://cloud.githubusercontent.com/assets/6171742/15113091/7f261dd4-15f2-11e6-94f5-088bf66e248a.png)

I've also changed the permissions so that the "User" resource is available for anonymous users:
![image](https://cloud.githubusercontent.com/assets/6171742/15113126/b0527fd8-15f2-11e6-89ac-8c0e7445e9a6.png)

When I try to authenticate a user I get this in chrome console:
![image](https://cloud.githubusercontent.com/assets/6171742/15113206/2f36fa22-15f3-11e6-9e5a-3a019218b852.png)

I've been able to fetch other data like nodes and views with angular-drupal on this installation of D8, but authentication is not working for me...

I've been banging my head on this for a while now, any suggestions on what I can try?

**Comment by signalpoint** [comment]
@EnzoEghermanne It looks like you are using the Drupal 7 version of angular-drupal. Be sure to grab the Drupal 8 version, which is actually just a wrapper around jDrupal 8.

**Comment by signalpoint** [comment]
@EnzoEghermanne Thank you for pointing this out though, I can see that the D8 docs for this project (specifically the README) are not correct. Since the `drupal` service is just a wrapper around jDrupal, you should be able to use the jDrupal 8 docs, and just use `drupal` instead of `jDrupal`: http://jdrupal.easystreet3.com/8/docs/

**Comment by e2o** [comment]
@signalpoint I was about to point that out, the readme says Drupal 8 at the top but most of the examples are methods for D7.

Also, the minified version of angular-drupal, `build/angular-drupal.min.js`, still has the D7 code in it. That's why i was messing up, because I tried to used to minified version, which isn't just the new D8 wrapper.

Thanks for the help, I figured it out now.

**Comment by e2o** [comment]
@signalpoint By the way, I really like the angular wrapper and jDrupal, great work man!

**Comment by kentr** [comment]
Created:
- #26 for `angular-drupal.min.js`.
- #27 for `README` examples.

**Comment by kentr** [comment]
@EnzoEghermanne Something missing with the simple `jDrupal` wrapper is binding via the Angular digest cycle.

I've been meaning to go through and create decorators to wrap the promises & async calls in Angular `$q` promises and whatnot.  I'll look into putting my existing dev code in a dev branch soon.

**Comment by kentr** [comment]
LGTM

**Comment by signalpoint** [comment]
@EnzoEghermanne thank you for the kind words, we both have @kentr to thank for the ingenious wrapper around jDrupal.
