### ISSUE TITLE
403 Forbidden on saving a user (PATCH)

### ISSUE THREAD

**Issue by e2o** [signalpoint/angular-drupal#31]
Hello again,

When trying to edit any field on a user, i get a 403 forbidden on the PATCH to update that user, with the detailed error message:

`{"error":"Access denied on updating field 'name'."}`

Strange thing is, i'm not even updating/changing that field's value.

The code sample on which I get this error is the following:

```
var user = drupal.currentUser();
    user.entity.field_hobbies[0].value = "Programming, cooking, sports,...";
    user.save().then(function(){
        console.log("user saved successfully");
    });
```

My permissions in D8 are set up like this:
![image](https://cloud.githubusercontent.com/assets/6171742/15173093/4f6f3f30-175a-11e6-85ff-e9d97d1f7935.png)

And my REST settings:
![image](https://cloud.githubusercontent.com/assets/6171742/15173103/615231a8-175a-11e6-9905-6ac4f1349737.png)

Am I missing something here? I have no idea why i get the error on the 'name' field, even when I try to update the user without even changing any fields.

**Comment by signalpoint** [comment]
@EnzoEghermanne this is most likely related to this issue: https://www.drupal.org/node/2631774 - Although that issue is for updating comments, I think it's essentially the same problem in that Drupal thinks we're trying to update a protected value, and is rejecting it with an access denied.

In the mean time, you may be able to preprocess the request and remove the user name from the data that is being PATCHed: http://jdrupal.easystreet3.com/8/api/API.js.html

**Comment by e2o** [comment]
@signalpoint It seems like it is indeed related to that issue.

Could you give me a small example on how and where I would implement the _hook_rest_pre_process_ function? I can't figure out what to do with it...

**Comment by kentr** [comment]
@EnzoEghermanne As a quick & dirty test, does removing the `name` property allow the entity to save?  Something like this, with [delete](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete):

``` javascript
var user = drupal.currentUser();
    user.entity.field_hobbies[0].value = "Programming, cooking, sports,...";
    // Delete name b/c of https://www.drupal.org/node/2631774
    // This may require a cloned object to prevent altering the original entity.
    delete user.entity.name;
    user.save().then(function(){
        console.log("user saved successfully");
    });
```

**Comment by e2o** [comment]
@kentr I'm not at the office at the moment. I'll try it out first thing in the morning and keep u guys posted.

Thanks for the suggestion.

**Comment by e2o** [comment]
@kentr You were right, it was because the request tried to PATCH the disallowed fields _name, created, changed_ and _roles_, even though they were unaltered.  So this is what I did:

``` javascript
var user = drupal.currentUser();
user.entity.field_hobbies[0].value = "Programming, cooking, sports,...";
delete user.entity.name;
delete user.entity.created;
delete user.entity.changed;
delete user.entity.roles;
user.save().then(function(){
    console.log("user saved successfully");
});
```

Which resulted in:
![image](https://cloud.githubusercontent.com/assets/6171742/15206562/6462d066-1820-11e6-959c-6aa7fae7e519.png)

Thanks for the help!

**Comment by kentr** [comment]
Glad to know it worked.

As I thought about it this morning, I wondered if granting Drupal's **Change own username** permission would allow the `name` field to be in the PATCH (at `admin/people/permissions`).

**Comment by e2o** [comment]
I'll try it out next week, but if I recall correctly that was something I already tried out. Will keep u posted.

EDIT: Tested out the permissions as proposed, the 403 Patch forbidden on field name appeared again.
So I guess just deleting these entities before saving is the only option for now.
