### ISSUE TITLE
How to upload images to image field? 7.x

### ISSUE THREAD

**Issue by fufu7755** [signalpoint/angular-drupal#42]
Hi @signalpoint,
I build a app with angular and ionic,I want to use cordova plugin to upload images to image field.Please give me some advice on how to implement this process. If you have the relevant demo code is better.
Thank you very much.

**Comment by signalpoint** [comment]
@fufu7755 I'd use the File plugin with Cordova, then use it to retrieve a base 64 encoded string of your image, then follow this example to get the picture into Drupal: http://tylerfrankenstein.com/code/drupal-services-file-create-example-json-and-jquery - just change the jQuery to Angular syntax

**Comment by fufu7755** [comment]
Hi @signalpoint thank you for your reply. Now, I have get the image and retrieve it to base 64 encoded string, then I use drupal.file_save function to save it, but return me a error message "Not found : Could not find resource file.". Please give me some help again.Thank you.
![wechatimg1](https://cloud.githubusercontent.com/assets/7938785/22324916/a319e438-e3e6-11e6-99cb-a6cf19033aae.jpeg)

**Comment by signalpoint** [comment]
@fufu7755 You need to turn on the `File` service and subsequent `Resources` in Drupal here:

`admin/structure/services/list/[my-endpoint-name]/resources`

You need to enable the `Create` resource and grant permissions for user role(s) to use the `Save binary file` permission. Then flush Drupal's caches, and that should fix it.

Once completed, it'll return to you the new file id from Drupal.

**Comment by fufu7755** [comment]
@signalpoint Thank you very much!

**Comment by signalpoint** [comment]
@fufu7755 You're welcome. After that you can just make a node save/update call and send along this JSON without the node object:

```
field_my_image: {
  und: [
    { fid: 123 }
  ]
}
```

That'll set the file id onto the field for your node, good luck!
